name: futurist_recommendation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.2
  - numpy=1.26.4
  - pandas=2.1.4
  - scikit-learn=1.3.2
  - xgboost=3.0.5
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - joblib=1.5.2
  - pillow=10.2.0
  - requests=2.31.0
  - python-dotenv=1.1.1
  - pip:
      - imbalanced-learn==0.12.3
      - tensorflow==2.20.0
      - torch==2.8.0
      - torchvision==0.23.0
      - sentence-transformers==5.1.1
      - clip-anytorch==2.6.0
      - plotly==6.3.1
      - dash==3.2.0
      - fastapi==0.118.0
      - uvicorn==0.37.0
      - pymongo==4.15.2
      - tqdm==4.65.0
      - transformers==4.56.2
      - ftfy==6.3.1
      - safetensors==0.6.2
      - tensorboard==2.20.0
      - h5py==3.14.0
      - absl-py==2.3.1
      - ml-dtypes==0.5.3
      - opt_einsum==3.4.0
      - google-pasta==0.2.0
      - gast==0.6.0
      - sympy==1.14.0
      - typing-extensions==4.15.0
      - starlette==0.48.0
      - en-core-web-sm==3.8.0
